In [2]:
import pandas as pd
import json

In [3]:
features = pd.read_csv('./data/u00_features.csv')

In [4]:
features = features.fillna(0)

In [4]:
sensing = pd.read_csv('./data/u00_sensing_data.csv')

In [5]:
sensing

,timestamp,conversation,bt_level_avg,bt_level_std,bt_total_devices_around,bt_total_far,bt_total_farther,bt_total_near,bt_total_nearer,wifi_level_avg,...,phone_charging,phone_locked,activity_inference_0,activity_inference_1,activity_inference_2,activity_inference_3,audio_inference_0,audio_inference_1,audio_inference_2,audio_inference_3
0,2013-03-27 04:00:00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.000000,...,0.0,0.0,599.0,0.0,0.0,0.0,274.0,0.0,185.0,140
1,2013-03-27 04:10:00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,600.0,0.0,0.0,0.0,557.0,1.0,42.0,0
2,2013-03-27 04:20:00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-71.500000,...,0.0,0.0,600.0,0.0,0.0,0.0,457.0,0.0,143.0,0
3,2013-03-27 04:30:00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,315.0,208.0,600.0,0.0,0.0,0.0,564.0,1.0,35.0,0
4,2013-03-27 04:40:00,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-62.000000,...,600.0,600.0,600.0,0.0,0.0,0.0,127.0,94.0,379.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9482,2013-06-01 00:20:00,600.0,-95.0,NaN,1.0,0.0,1.0,0.0,0.0,-82.710526,...,0.0,0.0,261.0,337.0,0.0,2.0,58.0,394.0,148.0,0
9483,2013-06-01 00:30:00,600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-83.052632,...,0.0,0.0,315.0,281.0,0.0,4.0,90.0,407.0,103.0,0
9484,2013-06-01 00:40:00,600.0,-95.0,NaN,1.0,0.0,1.0,0.0,0.0,-77.394737,...,0.0,0.0,418.0,182.0,0.0,0.0,162.0,315.0,123.0,0
9485,2013-06-01 00:50:00,390.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-81.769231,...,0.0,0.0,147.0,201.0,237.0,15.0,85.0,186.0,329.0,0
9486,2013-06-01 01:00:00,211.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.181818,...,0.0,0.0,206.0,0.0,0.0,11.0,104.0,66.0,47.0,0

In [5]:
import requests

In [25]:
requests.get("http://127.0.0.1:3500/api/get_metric/test/jixi")

In [32]:
headers = {'Content-Type': 'application/json'}
requests.post("http://127.0.0.1:3500/api/add_metric/test/", data=json.dumps([
  {"name": "jixi", "timestamp": "2020/10/03", "value": 10.0},
  {"name": "jixi", "timestamp": "2020/10/04", "value": 80.0},
  {"name": "jixi", "timestamp": "2020/10/05", "value": 20.0}
]), headers=headers)

In [6]:
features['name'] = 'Kevin'

In [13]:
df = pd.DataFrame([features['name'], features['timestamp'], features['conversation']])
df = df.rename(index={'conversation': 'value'})

data = list(df.to_dict().values())

In [ ]:
chunk_size = 100
sample_size = 200

for key in features.keys():
    if key not in ['name', 'timestamp']:
        df = pd.DataFrame([features['name'], features['timestamp'], features[key]])
        df = df.rename(index={key: 'value'})
        
        data = list(df.to_dict().values())[:sample_size]
        for i in range(len(data) // chunk_size - 1):
            requests.post(f"http://127.0.0.1:3500/api/add_metric/{key}/", data=json.dumps(data[i * chunk_size: (i + 1) * chunk_size]))